### ISSUE TITLE
Styling not applied to header on iOS

### ISSUE THREAD

**Issue by lukeramsden** [triniwiz/nativescript-accordion#14]
For some reason, none of the styles I'm putting on the `class` are actually being applied on iOS. It's applying to the text, but just not the header.

Here's my XML:

```xml
<accordion:Accordion items="{{ items }}" class="accordion" allowMultiple="false">
  <accordion:Accordion.headerTemplate>
    <StackLayout>
      <GridLayout rows="*" columns="2*, 2*, 2*, 20*, *" class="header">
        <StackLayout row="0" col="1" colSpan="3" class="header-bg" />
        <StackLayout row="0" col="0" colSpan="2" class="key-bg" verticalAlignment="middle">
          <Label text="{{ key }}" class="key" textWrap="false" />
        </StackLayout>
        <StackLayout row="0" col="2" colSpan="2" verticalAlignment="middle">
          <Label text="{{ title }}" class="title" textWrap="true" />
        </StackLayout>
      </GridLayout>
    </StackLayout>
  </accordion:Accordion.headerTemplate>
  <accordion:Accordion.itemTemplate>
    <Label text="{{ text }}" class="text" textWrap="true" />
  </accordion:Accordion.itemTemplate>
</accordion:Accordion>
```

and my CSS:

```css
Page {
  background-color: #F3721F;
}

.header {
  margin: 10;
  margin-left: 0;
}

.header-bg {
  padding: 25, 5;
  background-color: #151515;
  border-color: #FFFFFF;
  border-width: 1;
}

.title {
  font-size: 16px;
  color: #FFFFFF;
  margin: 0, 10;
}

.key-bg {
  background-color: #F3721F;
  border-color: #FFFFFF;
  border-width: 1;
  border-radius: 50%;
  width: 35;
  height: 35;
  padding: 0;
  margin: 1;
}

.key {
  font-family: 'Montserrat';
  text-align: center;
  vertical-align: middle;
  color: #FFFFFF;
  font-size: 18px;
  margin-top: 1;
}

.text {
  border-top-color: #FFFFFF;
  border-top-width: 1;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 1;
  color: #FFFFFF;
  padding: 10, 40;
  background-color: #151515;
  vertical-align: middle;
  horizontal-align: center;
}
```
